import './globals.css';
import Navbar from '@/components/Navbar';
import LeftSidebar from '@/components/LeftSidebar';
import Provider from './providers/sessionProvider';
import NextAuth from 'next-auth/next';

export const metadata = {
  title: 'TikTok | Make Your Day',
  description: 'Generated by create next app',
};

export default async function Layout({ children }: { children: React.ReactNode }) {
  
  return (
    <html lang="en">
      <body>
        <Provider>
        <div className="mx-6">
          <Navbar />
          <div className="flex relative">
            <div className="sticky">
              <LeftSidebar />
            </div>
            {children}
          </div>
        </div>
        </Provider>
      </body>
    </html>
  );
}
