import Head from 'next/head'
import './globals.css'
import Navbar from '@/components/Navbar'
import LeftSidebar from '@/components/LeftSidebar'

export const metadata = {
  title: 'TikTok | Make Your Day',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Head>
        <link rel="stylesheet" href="/favicon.ico" />
      </Head>
      <body>
        <div className='mx-6'>
        <Navbar />
        <div className='flex relative '>
          <div className='sticky'>
          <LeftSidebar />
          </div>
          {children}
        </div>
        </div>
        </body>
    </html>
  )
}
